SJVAir/sjvair.com

- assets/map/components/MonitorGraph.vue
- assets/map/utils/GraphData.js
Corrects loading of graph data by converting `GraphData` to a singleton. This allows us to abstract control of it's scope to ensure persistent data and strict control of instance generation.
> Fix Graph Data Loading

- assets/js/bulma-tabs.js
- assets/sass/sjvair/components/bulma-tabs.sass
- assets/sass/sjvair/pages/api.sass
- assets/sass/style.sass
- camp/api/middleware.py
- camp/api/urls.py
- camp/api/v1/monitors/endpoints.py
- camp/api/v1/urls.py
- camp/settings/base.py
- camp/template_tags.py
- camp/templates/api/endpoint-get.html
- camp/templates/pages/api.html
- camp/templates/pages/guidelines.html
- camp/utils/test.py
This PR updates the `/api/` url to display some reference documentation for our API endpoints, including a new endpoint specifically for methane data.
> Add API docs, methane data endpoint.

- package.json
- yarn.lock
This PR holds no new features, and solely updates the dependencies for the Map Component.
> Vue: Map Component Dependencies

- package.json
- yarn.lock
Bumps @sjvair/monitor-map package to v1.2.5
> updates @sjvair/monitor-map dependency

- package.json
- yarn.lock
Updates @sjvair/monitor-map to 1.22.0
> updates @sjvair/monitor-map dep

- camp/api/v1/monitors/endpoints.py
- camp/api/v1/monitors/serializers.py
- camp/api/v1/monitors/urls.py
- camp/utils/forms.py
Adds `/monitors/closest` endpoint
> Feat: Closest Monitor Endpoint

- camp/api/v1/monitors/endpoints.py
Corrects query exclusion and excludes indoor monitors
> Fix: Closest Monitors Endpoint

- camp/apps/monitors/models.py
- package.json
- yarn.lock
Re-enable calibrations and update monitor map dependency
> Re-enable Calibrations

- camp/apps/calibrations/linreg.py
This updated calibration is not yet enabled, but we want to start seeing the formulas over time.
> Update calbration formula to be based purely on existing PM2.5

- package.json
- yarn.lock
The url generation for the widget has been altered to utilize the window url instead of the url the file was served from
> Fix: Widget URL

- camp/apps/alerts/admin.py
- camp/apps/alerts/views.py
- camp/templates/admin/alerts/subscription/county_stats.html
- camp/templates/admin/index.html
- camp/utils/counties.py
Title says it all, here's what it looks like on my local machine:
> Add admin screen showing monitor subscription stats broken up by county.

- package.json
- yarn.lock
Updates `@sjvair/monitor-map` to version 1.7.1
> updates @sjvair/monitor-map

- package.json
- yarn.lock
Updates @sjvair/monitor-map to version 1.7.2
> Chore: Update @sjvair/monitor-map

- package.json
- yarn.lock
Updates @sjvair/monitor-map to 1.8.8; includes style tweaks for mobile
> Updates @sjvair/monitor-map to 1.8.8

- package.json
- yarn.lock
Updates @sjvair/monitor0map to 1.8.10; includes fix for AQview calibrators
> Updates @sjvair/monitor0map

- package.json
- yarn.lock
Updates @sjvair/monitor-map to 1.8.12; includes fix to prevent monitor names from being translated
> Updates @sjvair/monitor-map to 1.8.12

- package.json
- yarn.lock
@sjvair/monitor-map has been updated to 1.9.1
@sjvair/web-widget has been updated to 1.0.9
> Updates @sjvair Packages

- package.json
- yarn.lock
Updates @sjvair/monitor-map dependency to 1.9.4
> Update @sjvair/monitor-map Package

- package.json
- yarn.lock
Updates @sjvair/monitor-map dependency to 1.9.5
> Updates @sjvair/monitor-map to 1.9.5

- camp/apps/monitors/models.py
- camp/apps/monitors/purpleair/api.py
- camp/apps/monitors/purpleair/models.py
- camp/apps/monitors/purpleair/tasks.py
This PR integrates with the PA history API and adds a task for importing entries (or updating the recorded value of existing entries).
> PurpleAir Historical Imports
